import type { BadgeDefinition } from "./types";

export const BADGE_DEFINITIONS: BadgeDefinition[] = [
  // ── Exploration (6) ──────────────────────────────────────────────
  {
    id: "first-apparition",
    name: "First Apparition",
    description: "You materialized. Welcome to the other side.",
    category: "exploration",
    rarity: "common",
    icon: "Ghost",
    hidden: false,
    unlockHint: "Create an account",
  },
  {
    id: "ecto-trail",
    name: "Ecto Trail",
    description: "Your ectoplasm lingers across 5 topic pages.",
    category: "exploration",
    rarity: "common",
    icon: "Footprints",
    hidden: false,
    unlockHint: "Visit 5 different topic pages",
  },
  {
    id: "spectral-drift",
    name: "Spectral Drift",
    description: "Drifted through 7 different domains — a true wandering spirit.",
    category: "exploration",
    rarity: "uncommon",
    icon: "Compass",
    hidden: false,
    unlockHint: "Visit 1+ topic in 7 different domains",
  },
  {
    id: "phantom-surveyor",
    name: "Phantom Surveyor",
    description: "Surveyed every corner of the haunted grounds.",
    category: "exploration",
    rarity: "uncommon",
    icon: "Binoculars",
    hidden: false,
    unlockHint: "Visit all 15 domain hubs",
  },
  {
    id: "poltergeist-cartographer",
    name: "Poltergeist Cartographer",
    description: "Mapped the spectral realm across 10+ domains on the knowledge graph.",
    category: "exploration",
    rarity: "rare",
    icon: "Graph",
    hidden: false,
    unlockHint: "Interact with nodes from 10+ domains on the knowledge graph",
  },
  {
    id: "the-lurker",
    name: "The Lurker",
    description: "Always watching, always reading. 60+ minutes of accumulated knowledge.",
    category: "exploration",
    rarity: "common",
    icon: "Eye",
    hidden: false,
    unlockHint: "Spend 60+ cumulative minutes reading content",
  },

  // ── Mastery (7) ──────────────────────────────────────────────────
  {
    id: "possessed-by-knowledge",
    name: "Possessed by Knowledge",
    description: "Achieved total mastery of an entire domain. The knowledge possesses you now.",
    category: "mastery",
    rarity: "rare",
    icon: "Brain",
    hidden: false,
    unlockHint: "Complete every topic + cheatsheet in any single domain",
  },
  {
    id: "hex-reader",
    name: "Hex Reader",
    description: "Mastered Terminal & Tools — every command at your ghostly fingertips.",
    category: "mastery",
    rarity: "uncommon",
    icon: "Terminal",
    hidden: false,
    unlockHint: "Complete all content in Terminal & Tools domain",
  },
  {
    id: "phantom-protocol",
    name: "Phantom Protocol",
    description: "Every packet, every protocol — the network is your haunting ground.",
    category: "mastery",
    rarity: "uncommon",
    icon: "WifiHigh",
    hidden: false,
    unlockHint: "Complete all content in Networking domain",
  },
  {
    id: "memory-leak",
    name: "Memory Leak",
    description: "You've leaked into every corner of the operating system.",
    category: "mastery",
    rarity: "uncommon",
    icon: "Cpu",
    hidden: false,
    unlockHint: "Complete all content in Operating Systems domain",
  },
  {
    id: "shadow-architect",
    name: "Shadow Architect",
    description: "Designed the blueprints for the spectral realm.",
    category: "mastery",
    rarity: "rare",
    icon: "SquaresFour",
    hidden: false,
    unlockHint: "Complete all content in Software Engineering domain",
  },
  {
    id: "spectral-cipher",
    name: "Spectral Cipher",
    description: "Cracked every cipher — no encryption can contain your spirit.",
    category: "mastery",
    rarity: "rare",
    icon: "ShieldCheck",
    hidden: false,
    unlockHint: "Complete all content in Cybersecurity domain",
  },
  {
    id: "neural-phantom",
    name: "Neural Phantom",
    description: "Fused with the neural network. AI recognizes you as one of its own.",
    category: "mastery",
    rarity: "rare",
    icon: "Atom",
    hidden: false,
    unlockHint: "Complete all content in AI & ML domain",
  },

  // ── Codex & Cheatsheets (5) ──────────────────────────────────────
  {
    id: "grimoire-initiate",
    name: "Grimoire Initiate",
    description: "Opened your first page of the Codex. The grimoire chose you.",
    category: "codex",
    rarity: "common",
    icon: "BookOpen",
    hidden: false,
    unlockHint: "Read your first codex article",
  },
  {
    id: "tome-collector",
    name: "Tome Collector",
    description: "Collected 10 codex tomes. Your spectral library grows.",
    category: "codex",
    rarity: "uncommon",
    icon: "Books",
    hidden: false,
    unlockHint: "Read 10 codex articles",
  },
  {
    id: "quick-seance",
    name: "Quick Séance",
    description: "Channeled your first cheatsheet — quick reference from beyond.",
    category: "codex",
    rarity: "common",
    icon: "Lightning",
    hidden: false,
    unlockHint: "View your first cheatsheet",
  },
  {
    id: "ectoplasmic-reference",
    name: "Ectoplasmic Reference",
    description: "10 cheatsheets consulted. Your reference game is supernatural.",
    category: "codex",
    rarity: "uncommon",
    icon: "Table",
    hidden: false,
    unlockHint: "View 10 different cheatsheets",
  },
  {
    id: "the-necronomicon",
    name: "The Necronomicon",
    description: "Every codex article consumed. You've read the forbidden texts.",
    category: "codex",
    rarity: "epic",
    icon: "BookBookmark",
    hidden: false,
    unlockHint: "Read every codex article",
  },

  // ── Streaks (4) ──────────────────────────────────────────────────
  {
    id: "haunt-streak",
    name: "Haunt Streak",
    description: "7 days of relentless haunting. The living grow uneasy.",
    category: "streaks",
    rarity: "common",
    icon: "Fire",
    hidden: false,
    unlockHint: "Achieve a 7-day visit streak",
  },
  {
    id: "restless-spirit",
    name: "Restless Spirit",
    description: "30 consecutive days. You cannot be put to rest.",
    category: "streaks",
    rarity: "rare",
    icon: "FireSimple",
    hidden: false,
    unlockHint: "Achieve a 30-day visit streak",
  },
  {
    id: "the-eternal-haunt",
    name: "The Eternal Haunt",
    description: "100 days without rest. You've transcended mortality.",
    category: "streaks",
    rarity: "epic",
    icon: "Flame",
    hidden: false,
    unlockHint: "Achieve a 100-day visit streak",
  },
  {
    id: "witching-hour",
    name: "Witching Hour",
    description: "You visited during the witching hour — 12 AM to 4 AM.",
    category: "streaks",
    rarity: "common",
    icon: "Moon",
    hidden: false,
    unlockHint: "Visit between midnight and 4 AM",
  },

  // ── Completionist (3) ────────────────────────────────────────────
  {
    id: "full-possession",
    name: "Full Possession",
    description: "Every topic, every cheatsheet, every domain. Total possession achieved.",
    category: "completionist",
    rarity: "legendary",
    icon: "Crown",
    hidden: false,
    unlockHint: "Complete every piece of content across all 15 domains",
  },
  {
    id: "path-walker",
    name: "Path Walker",
    description: "Walked an entire learning path from start to finish.",
    category: "completionist",
    rarity: "epic",
    icon: "Path",
    hidden: false,
    unlockHint: "Complete an entire learning path",
  },
  {
    id: "astral-collector",
    name: "Astral Collector",
    description: "Earned every non-hidden badge. The ultimate collector.",
    category: "completionist",
    rarity: "legendary",
    icon: "Trophy",
    hidden: false,
    unlockHint: "Earn all other non-hidden badges",
  },

  // ── Hidden (3) ───────────────────────────────────────────────────
  {
    id: "glitch-in-the-matrix",
    name: "Glitch in the Matrix",
    description: "You found a glitch. Reality is not what it seems.",
    category: "hidden",
    rarity: "epic",
    icon: "Bug",
    hidden: true,
    unlockHint: "???",
  },
  {
    id: "the-original-ghost",
    name: "The Original Ghost",
    description: "One of the first 100 spirits to inhabit this realm.",
    category: "hidden",
    rarity: "legendary",
    icon: "Skull",
    hidden: true,
    unlockHint: "???",
  },
  {
    id: "reverse-engineer",
    name: "Reverse Engineer",
    description: "Read the Hacker Mindset backwards. Some secrets only reveal themselves in reverse.",
    category: "hidden",
    rarity: "common",
    icon: "MagnifyingGlass",
    hidden: true,
    unlockHint: "???",
  },
];

/** Map of badge ID to definition for quick lookup */
export const BADGE_MAP = new Map(
  BADGE_DEFINITIONS.map((b) => [b.id, b])
);

/** Category labels for display */
export const CATEGORY_LABELS: Record<string, string> = {
  exploration: "Exploration",
  mastery: "Mastery",
  codex: "Codex & Cheatsheets",
  streaks: "Streaks",
  completionist: "Completionist",
  hidden: "Hidden",
};

/** Category display order */
export const CATEGORY_ORDER = [
  "exploration",
  "mastery",
  "codex",
  "streaks",
  "completionist",
  "hidden",
] as const;
